### ISSUE TITLE
Нарисуй палочку, двинь её туда

### ISSUE THREAD

**Issue by Kyrraga** [Kyrraga/PyPong#1]
Для начала нам нужно научится рисовать объекты. Для начала будем рисовать палочки 1x3. Цвет любой (кроме цвета фона) ,если есть возможность менять, то ещё лучше. Также требуется сделать их передвижение. Запрещается выходить за пределы поля. Посередине есть разделяющая полоса, дабы игроки не могли залезать на чужую сторону поля

**Comment by Kinrany** [comment]
Можно закрывать?
